version: '3.7'

services:
  web-bff-onboard:
    container_name: web-bff-onboard-dev
    build: 
      context: .
      dockerfile: ./docker/dev/images/web-bff-onboard/Dockerfile
    restart: always
    ports:
      - 3334:3334

  auth-ms-backend:
    container_name: auth-ms-backend-dev
    build: 
      context: .
      dockerfile: ./docker/dev/images/auth-ms-backend/Dockerfile
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3333:3333

  email-ms-backend:
    container_name: email-ms-backend-dev
    build: 
      context: .
      dockerfile: ./docker/dev/images/email-ms-backend/Dockerfile
    restart: always
    depends_on:
      - mongo
      - rabbitmq

  postgres:
    build: ./docker/dev/images/postgresql
    container_name: postgres-dev
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./documents/blacklist-taxvats.txt:/documents/blacklist-taxvats.txt
      - ./documents/disposable-emails.txt:/documents/disposable-emails.txt
      - ./scripts/dev/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  rabbitmq:
    build: ./docker/dev/images/rabbitmq
    container_name: rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    build: ./docker/dev/images/mongo
    container_name: mongo-dev
    volumes:
      - ./scripts/dev/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
      - mongo_data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      MONGO_INITDB_DATABASE: "admin"

  mongo-express:
    image: mongo-express
    container_name: mongo-express-dev
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    depends_on:
      - mongo

volumes:
  postgres_data: {}
  mongo_data: {}
