version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: clean-node-login-api-ts-postgres-dev
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    volumes:
      - ./scripts/dev/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
volumes:
  postgres_data: {}